### ISSUE TITLE
Raspberry Instructions Update

### ISSUE THREAD

**Issue by andifds** [InstaPy/instapy-docs#5]
Used the [current instructions](https://github.com/InstaPy/instapy-docs/blob/master/How_Tos/How_to_Raspberry.md#install-instapy) to install InstaPy on Raspberry Pi availables on docs, but not working very well.

Personally I suggest to update that doc to this instructions that resulted work better. This because on current commands the instapy- chromedriver uninstall and then installation of 2.36.post0 doesn't work.

Theses are my suggested steps for a clean Raspbian Strech Lite install
## Install InstaPy
1. ```sudo apt-get update && sudo apt-get -y upgrade```
2. ```sudo apt-get install chromium-browser```
3. ```sudo apt-get install python3-pip```
4. ```sudo pip3 install instapy```
5. ```sudo pip3 uninstall instapy-chromedriver```
6. ```sudo pip3 install instapy-chromedriver==2.36.post0```
7. ```sudo reboot``` (optional)
8. ```mkdir InstaPy Scripts```
_(Do not confuse with "InstapPy" dir, that will be created automatically after first use which contais "db", "logs" and "assets" sub-directories)_
9. ```cd InstaPy Scripts```
10. ```nano quickstart.py```
11. Edit quickstart file with your credentials/ add functions you want to use, documentation in the main [Readme](https://github.com/timgrossmann/InstaPy/blob/master/README.md)
12. ```sudo python3 quickstart.py```

## How to update on Raspberry Pi
Keep your setup updated, but keeping ```instapy-chromedriver==2.36.post0```

1. ```sudo pip3 install instapy -U```
2. ```sudo pip3 uninstall instapy-chromedriver```
3. ```sudo pip3 install instapy-chromedriver==2.36.post0```

Here's [another user request](https://github.com/timgrossmann/InstaPy/issues/4033#issuecomment-476410775) to update current Readme for RPi with proposed instructions. To suggest directly this update on current files is necessary to make a commit?

**Comment by Gabbo94** [comment]
Even with this procedure i get this error:
pi@raspberrypi:~/InstaPyScripts $ python3 quickstart.py
/home/pi/.local/lib/python3.5/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/pi/InstaPy"

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
INFO [2019-04-27 20:49:00] [bolognarepartocorseofficial]  Using built in instapy-chromedriver executable (version 2.36.post0)
ERROR [2019-04-27 20:50:02] [bolognarepartocorseofficial]  Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/browser.py", line 146, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)

Traceback (most recent call last):
  File "quickstart.py", line 11, in <module>
    headless_browser=False)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 295, in __init__
    self.set_selenium_local_session()
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 349, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver

**Comment by Gabbo94** [comment]
> Even with this procedure i get this error:
> pi@raspberrypi:~/InstaPyScripts $ python3 quickstart.py
> /home/pi/.local/lib/python3.5/site-packages/requests/**init**.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
> RequestsDependencyWarning)
> 
> ._. ._. ._. ._. ._. ._. ._. ._.
> Workspace in use: "/home/pi/InstaPy"
> 
> ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._.
> INFO [2019-04-27 20:49:00] [bolognarepartocorseofficial] Using built in instapy-chromedriver executable (version 2.36.post0)
> ERROR [2019-04-27 20:50:02] [bolognarepartocorseofficial] Message: unknown error: Chrome failed to start: exited abnormally
> (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)
> Traceback (most recent call last):
> File "/home/pi/.local/lib/python3.5/site-packages/instapy/browser.py", line 146, in set_selenium_local_session
> chrome_options=chrome_options)
> File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in **init**
> desired_capabilities=desired_capabilities)
> File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in **init**
> self.start_session(capabilities, browser_profile)
> File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
> response = self.execute(Command.NEW_SESSION, parameters)
> File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> self.error_handler.check_response(response)
> File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> raise exception_class(message, screen, stacktrace)
> selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
> (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)
> 
> Traceback (most recent call last):
> File "quickstart.py", line 11, in 
> headless_browser=False)
> File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 295, in **init**
> self.set_selenium_local_session()
> File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 349, in set_selenium_local_session
> raise InstaPyError(err_msg)
> instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver

P.S. 
I notice that at point 8. you wrote "mkdir InstaPy Scripts". I think that your intention was to create a single directory named "InstaPy Scripts" but when i try to do it, i saw that the raspberry has created 2 different directories named "InstaPy" and "Scripts". This is why i named it InstaPyScripts

**Comment by Gabbo94** [comment]
> > Even with this procedure i get this error:
> > pi@raspberrypi:~/InstaPyScripts $ python3 quickstart.py
> > /home/pi/.local/lib/python3.5/site-packages/requests/**init**.py:91: RequestsDependencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported version!
> > RequestsDependencyWarning)
> > ._. ._. ._. ._. ._. ._. ._. ._.
> > Workspace in use: "/home/pi/InstaPy"
> > ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._. ._.
> > INFO [2019-04-27 20:49:00] [bolognarepartocorseofficial] Using built in instapy-chromedriver executable (version 2.36.post0)
> > ERROR [2019-04-27 20:50:02] [bolognarepartocorseofficial] Message: unknown error: Chrome failed to start: exited abnormally
> > (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)
> > Traceback (most recent call last):
> > File "/home/pi/.local/lib/python3.5/site-packages/instapy/browser.py", line 146, in set_selenium_local_session
> > chrome_options=chrome_options)
> > File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in **init**
> > desired_capabilities=desired_capabilities)
> > File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in **init**
> > self.start_session(capabilities, browser_profile)
> > File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
> > response = self.execute(Command.NEW_SESSION, parameters)
> > File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
> > self.error_handler.check_response(response)
> > File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
> > raise exception_class(message, screen, stacktrace)
> > selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
> > (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)
> > Traceback (most recent call last):
> > File "quickstart.py", line 11, in
> > headless_browser=False)
> > File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 295, in **init**
> > self.set_selenium_local_session()
> > File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 349, in set_selenium_local_session
> > raise InstaPyError(err_msg)
> > instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver
> 
> P.S.
> I notice that at point 8. you wrote "mkdir InstaPy Scripts". I think that your intention was to create a single directory named "InstaPy Scripts" but when i try to do it, i saw that the raspberry has created 2 different directories named "InstaPy" and "Scripts". This is why i named it InstaPyScripts

Solved, i change the permission of the chromedriver both in home/Pi/InstaPy/Assets/chromedriver and home/Pi/.local/lib/python3.5/site-packages/instapy_chromedriver/chromedriver.
Also i added a directory home/Pi/.local/lib/python3.5/dist-packages because i see that a script linked to it. Finally i added a sub directory with the driver home/Pi/.local/lib/python3.5/dist-packages/instapy_chromedriver/chromedriver

Now the error is:
pi@raspberrypi:~/InstaPyScripts $ python3 quickstart.py
/home/pi/.local/lib/python3.5/site-packages/requests/__init__.py:91: RequestsDep                                                                                                             endencyWarning: urllib3 (1.25.1) or chardet (3.0.4) doesn't match a supported ve                                                                                                             rsion!
  RequestsDependencyWarning)

 ._.  ._.  ._.  ._.  ._.  ._.  ._.  ._.
Workspace in use: "/home/pi/InstaPy"
ERROR [2019-04-28 00:55:52] [bolognarepartocorseofficial]  Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)
Traceback (most recent call last):
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/browser.py", line 146, in set_selenium_local_session
    chrome_options=chrome_options)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/chrome/webdriver.py", line 81, in __init__
    desired_capabilities=desired_capabilities)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 157, in __init__
    self.start_session(capabilities, browser_profile)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 252, in start_session
    response = self.execute(Command.NEW_SESSION, parameters)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/pi/.local/lib/python3.5/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: Chrome failed to start: exited abnormally
  (Driver info: chromedriver=2.36 (a81166ad79e68fbfe7cf5ba243192d6412e26b37),platform=Linux 4.14.98-v7+ armv7l)

Traceback (most recent call last):
  File "quickstart.py", line 11, in <module>
    headless_browser=False)
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 295, in __init__
    self.set_selenium_local_session()
  File "/home/pi/.local/lib/python3.5/site-packages/instapy/instapy.py", line 349, in set_selenium_local_session
    raise InstaPyError(err_msg)
instapy.exceptions.InstaPyError: ensure chromedriver is installed at /home/pi/InstaPy/assets/chromedriver
